### ISSUE TITLE
How to synchronize samples with csound-expression tracks?

### ISSUE THREAD

**Issue by RichardWarfield** [spell-music/csound-sampler#1]
Apologies for asking such a basic question but I've been trying to figure this out for a day without luck.

I have an instrument track created with csound-expression.  This has signature:

```haskell
drumTrack :: Sco (Mix (Sig, Sig))
```

Which is constructed from a `Track`.  Then I have my sample of type `Sam`.  My goal is to loop the sample and have a repetition start on every eighth beat (say).  How can I accomplish this?  Based on the types I figured I can play both at the same time by doing something like:

```haskell
dac $  do 
  sm <- runSam 128 (loop mySample)
  return $ mean [mix drumTrack, sm]
```

The BPM arguments seems like it should be the key, but it doesn't seem to do anything.

**Comment by anton-k** [comment]
Hi, Richard!

Thanks for the question!

general idea is to stretch (`str`) the track with given bpm and use `toSam` or
`limSam` to lift the signal produced with mix+sco to the Sam- data type. 
By default all singleton tracks are playing once per second (created with `temp`).
But we can change the speed with `str`. So if we create a `Track` we can align it
to the global BPM of the sampler.

here is the small example:

Lets import drum loop with 162 bpm

```haskell
drums = loop $ wav "Hid 162.wav"
```

Then we can create `Track`:

```haskell
instr cps = return $ linseg [1, 0.25, 0] * osc (sig cps)
arp = loop $ limSam 8 $ mix $ str (0.25 *  120 / 162) $ loopBy 16 $ sco instr $ mel $ fmap (temp . cpspch) [8.00, 8.02, 8.04, 8.07]```
```

you can see how we stretch the track to align the tempo
Now we can play them together:

```haskell
dac $ runSam (162 * 4) $ drums + arp
```

But what if we don't want to fix the bpm? One thing we can do is to create top-level 
bpm definition and use it:

```
myBpm = 162


mix $ str (0.25 *  120 / myBpm)

dac $ runSam (myBpm * 4) $ drums + arp
```

But there is a better way, function:

```haskell
withBpm :: (Bpm -> Sample a) -> Sample a 
```

It passes the bpm from `runSam` to the local scope. So we can use it like this:

```haskell
arp = withBpm $ \bpm -> loop $ limSam 8 
   $ mix $ str (120 / bpm) 
   $ loopBy 16 
   $ sco instr $ mel $ fmap (temp . cpspch) [8.00, 8.02, 8.04, 8.07]
```

there are two bugs to notice, sorry to say it but the `Track`- related portion of CE can be really buggy:

* conceptual bug for `str` instance for `Sam` and `Track`, they have reciprocal instances for the first parameter, the multiplication by ratio for `Sam` divides for `Track`, should really fix it

* another bug, I found by answering to your question :(
  The CE tries to be smart to calculate the stop-time of track if we use Tracks.
   So if it sees the Track, it calculates the duration of it and stops the track at it.
   This can help us. But for this example it fails to notice that Track becomes an
  argument of infinite loop, so we can not stop it.

Sorry for inconvenience. I'm trying to do my best. But sometimes it's not enough(

**Comment by RichardWarfield** [comment]
Thanks Anton for the very detailed explanation.  I'll give that a shot.  Really appreciate your work on this library!
